<!DOCTYPE html>
<html>	
<head>
	<title><?=$pagedata['title']." - ".$GLOBALS['site']['title']?></title>		
	
	<!-- Meta -->
	<meta charset="utf-8">    	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">	       
</head>

<body>

<!-- --------------------------- CSS Defaults ---------------------------  -->

<link href="/~buying28/css/bootstrap.min.css" rel="stylesheet">
<link href="/~buying28/css/font-awesome.css" rel="stylesheet">
<link href="/~buying28/css/animate.css" rel="stylesheet">
<link href="/~buying28/css/lib/jQueryUI/jquery-ui-1.10.4.custom.min.css" rel="stylesheet">

<!-- --------------------------- CSS Libs ---------------------------  -->
<!-- Toastr style -->
<link href="/~buying28/css/lib/toastr/toastr.min.css" rel="stylesheet">
<!-- Chosen CSS -->
<link href="/~buying28/css/lib/chosen/chosen.css" rel="stylesheet">
<!-- Gritter -->
<link href="/~buying28/js/lib/gritter/jquery.gritter.css" rel="stylesheet">

<!-- Summer Note -->
<link href="/~buying28/css/lib/summernote/summernote.css" rel="stylesheet"></link>
<link href="/~buying28/css/lib/summernote/summernote-bs3.css" rel="stylesheet"></link>

<!-- Data Tables -->
<link href="/~buying28/css/lib/dataTables/dataTables.bootstrap.css" rel="stylesheet">
<link href="/~buying28/css/lib/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="/~buying28/css/lib/dataTables/dataTables.tableTools.min.css" rel="stylesheet">
<link href="/~buying28/css/lib/dataTables/buttons.dataTables.min.css" rel="stylesheet">

<!-- Steps -->
<link href="/~buying28/css/lib/steps/jquery.steps.css" rel="stylesheet">

<link href="/~buying28/css/lib/daterangepicker/daterangepicker-bs3.css" rel="stylesheet">
<link href="/~buying28/css/lib/datepicker/datepicker3.css" rel="stylesheet">

<link href="/~buying28/css/lib/switchery/switchery.css" rel="stylesheet"> 
<link href="/~buying28/css/lib/dropzone/basic.css" rel="stylesheet">
<link href="/~buying28/css/lib/dropzone/dropzone.css" rel="stylesheet">

<link href="/~buying28/css/lib/footable/footable.core.css" rel="stylesheet">

<link href="/~buying28/js/lib/seatingcharts/css/tuMap.css" rel="stylesheet">

<link href="/~buying28/css/lib/jasny/jasny-bootstrap.min.css" rel="stylesheet">


<!-- --------------------------- CSS Custom ---------------------------  -->
<link href="/~buying28/css/style.css" rel="stylesheet">
<link href="/~buying28/css/site.less" rel="stylesheet/less" type="text/css"/>



<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-56344fda61a3838d" async="async"></script>