<form class="search-form">
	<input type="hidden" name="action" value="search"/>
	<input type="hidden" name="page" value="0"/>
	<div class="row">
		<div class="col-sm-6">
			<div class="form-group">
				<label>Date Range</label>
				<input type="text" class="form-control daterangepicker" name="filter[range]">
			</div>
		</div>
		<div class="col-sm-6">
			<div class="form-group">
				<label>Type</label>
				<select class="form-control" name="filter[type]">
					<option value="">All</option>
					<option value="GeneralError">General Error</option>
					<option value="GeneralWarning">General Warning</option>
					<option value="PriceFloor">Price hit the floor</option>
					<option value="NoComps">No comps</option>
					<option value="NotPriced">Inventory not priced</option>			
					<option value="PriceDrop">Inventory price change</option>			
					<option value="OutlierCompete">Inventory competing with outlier</option>
				</select>
			</div>
		</div>
		<div class="col-sm-4 hidden">
			<div class="form-group">
				<label>Status</label>
				<select class="form-control" name="filter[unread]">
					<option value="">All</option>
					<option value="1">New</option>					
				</select>
			</div>
		</div>		
</form>
<div class="row">
	<div class="col-sm-12">		
		<hr>
		<a href="#" class="btn btn-block btn-danger btn-xs full-remove-all-a">Delete all alerts</a>		
	</div>
</div>
<div class="ibox-content">
	<div class="activity-stream full-container">		
	</div>
</div>			
<hr>
<div class="row actions">
	<div class="col-sm-10">
		<a href="#" class="btn btn-primary btn-block full-more-a">Load More</a>			
	</div>
	<div class="col-sm-2">
		<a href="#" class="btn btn-default btn-block full-move-a"><i class="fa fa-arrows"></i></a>
	</div>
</div>

