<h4>Account Info</h4>	

<table class="table">
	<tr>
		<td>Email: </td>
		<td>{{email}}</td>
	</tr>
	<tr>
		<td>Tier: </td>
		<td>{{tier}}</td>
	</tr>
	<tr>
		<td>Credit Card: </td>
		<td>{{account.cc_num}}</td>
	</tr>
	<tr>
		<td>Shipping Address: </td>
		<td>{{account.shipping_name}}<br>{{account.shipping_address1}}<br>{{account.shipping_address2}}<br>{{account.shipping_city}} {{account.shipping_sate}} {{account.shipping_zip}}<br>{{account.shipping_phone}}</td>
	</tr>    
	<tr>
		<td>Billing Address: </td>
		<td>{{account.billing_name}}<br>{{account.billing_address1}}<br>{{account.billing_address2}}<br>{{account.billing_city}} {{account.billing_sate}} {{account.billing_zip}}<br>{{account.billing_phone}}</td>
	</tr>
</table>
